import type { Metadata } from "next";
import { Geist, Geist_Mono  } from "next/font/google";
import "./globals.css";

import 'bootstrap/dist/css/bootstrap.min.css'; // BootstrapのCSSを読み込む
import AppNavbar from '../components/AppNavbar';
import { AuthProvider } from '@/context/AuthContext'; // AuthProviderをインポート


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider> {/* childrenとAppNavbarをProviderで囲む */}
          <AppNavbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
